name: dev

on: 
  push:
    branches : 
      - dev
  pull_request: 
    paths:
      - 'src/**'
      - 'pipelines/**'
      - '.github/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with :
          path : '.'
          fetch-depth: 0
      - name: Cake-mts-s-template
        run: >
          .\templates\mts-s-template\build.ps1
      - name: Cake-scaffolder
        run: >
          .\scaffolder\TcOpen.Scaffold\TcOpen.Scaffold.sln