name: nightly

on: 
  workflow_dispatch :
    branches :  
      - dev
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v2
        with :
          path : '.'
          fetch-depth: 0
      - name: Run Psake
	      env:
	        gh-public-repos: ${{ secrets.TCOPENTEMPLATESPAT  }}			
        run: >
          .\build.ps1    
